name: Playwright API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --no-cache -t bookstore-api-tests .

      - name: Run tests
        run: docker run --rm -e BASE_URL=https://fakerestapi.azurewebsites.net bookstore-api-tests